### ISSUE TITLE
folder-drag causes import error

### ISSUE THREAD

**Issue by bryantChhun** [brainglobe/napari-brainreg#4]
As per the readme instructions, doing a folder-drag import causes this error:

![image](https://user-images.githubusercontent.com/25647712/96662258-d5a2a300-1302-11eb-8c81-6536167e7fce.png)

But I can manually import all .tiff files in the folder.  My folders typically have:

a .log file
boundaries.tiff
volumes.csv
deformation_field_0.tiff
deformation_field_1.tiff
deformation_field_2.tiff
downsampled_standard.tiff
registered_hemispheres.tiff
registered_atlas.tiff
downsampled.tiff

**Comment by adamltyson** [comment]
Hi @bryantChhun, do you have an up to date version of brainreg? This plugin only works with the newest version (that also creates a json file).

**Comment by bryantChhun** [comment]
@adamltyson, brainreg is 0.2.1 and napari-brainreg is 0.1.2.  No Json is output, but i fully admit my data might not be ideally set up for a good segmentation -- will the json be written even if segmentation is poor?

**Comment by adamltyson** [comment]
Hi @bryantChhun, if there's no json file (`brainreg.json`) made then something weird is going on. It should be created right at the beginning, so it doesn't matter is the registration works well or not.

Your napari plugin however is out of date, so that might need updating.

Could you try creating a new conda environment, and install brainreg?
```
conda create --name brainreg_test python=3.8
conda activate brainreg_test
pip install brainreg
```

Then download the test data from [here](https://gin.g-node.org/cellfinder/data/raw/master/brainreg/test_brain.zip) (only 10mb), unzip, then run brainreg:
```
brainreg test_brain brainreg_output -v 50 40 40  --orientation psl --atlas allen_mouse_50um
```

I just did this, and got these files:
```
boundaries.tiff                   downsampled_standard.tiff
brainreg_2020-10-23_09-51-00.log  downsampled.tiff
brainreg.json                     registered_atlas.tiff
deformation_field_0.tiff          registered_hemispheres.tiff
deformation_field_1.tiff          volumes.csv
deformation_field_2.tiff
```

I can then drag the output directory into napari (the version installed by brainreg), and it works fine.

If this still fails, could you send the brainreg log file?

**Comment by bryantChhun** [comment]
I'll give this a shot today.  One thing to bear in mind is that I had to recompile niftyreg for my mac OS version.  I did not compile it using openMP if that matters.  If brainreg.json contains info from niftyreg, maybe that is the reason it's not generated?

**Comment by adamltyson** [comment]
It shouldn't be, it's really simple, just a list of parameters passed to brainreg, like the atlas used etc.

**Comment by bryantChhun** [comment]
@adamltyson HI Adam,  Thanks for the help.  Identified the bonehead error -- I was running brainreg from a clone (because i wanted to replace the backend with my niftyreg binaries).  So while I updated the environment's brainreg install, i was running the local clone, which was not updated.  JSON was generated and folder loads as expected!

Now ... hopefully I can get this data registered :-)
